import React from "react";
import Link from "../link";

export function Terms() {
	return (
		<div className="container">
			<div className="conditions-cont">
				<div className="row">
					<div className="col-md-8 offset-md-2">
						<div className="terms_titles">
							<h1>TERMS AND CONDITIONS</h1>
							<div className="custom-border"></div>
							<p>These Terms and Conditions (hereinafter “Terms”) is a binding legal agreement between you, whether personally or on behalf of an entity (“you“) and Cashero Financial OÜ (hereinafter “Company”, “Our”, “Us”, “We”, “Cashero") having its registered address at Keemia 4, Tallinn, Estonia 10616, concerning your access to and use of the Cashero App as well as any other media form, media channel, mobile website or mobile application related, linked, or service provided by Cashero, or otherwise connected thereto (collectively, the “App”). Both, individual (private persons) and business (corporate and institutions) customers are subjected to this agreement. These Terms are made to ensure quality and safety of use on the App. You agree that by accessing the App, you have read, understood, and agreed to be bound by all of these Terms. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE APP AND YOU MUST DISCONTINUE USE IMMEDIATELY. </p>
							<p>Supplemental terms and conditions or documents that may be posted on the App from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms at any time and for any reason. We will alert you about any changes by updating the “Last Updated” date of these Terms, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms to stay informed of updates. You will be subject to and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms by your continued use of the App after the date such revised Terms are posted. </p>
						</div>
						<div className="terms_titles">
							<h3>ELIGIBILITY</h3>
							<p>This information provided on the App is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the App from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
							<p>To access or use the App, you must be able to form a legally binding contract with us. Accordingly, you represent that you are at least eighteen years old, you are of legal age and capabilities to form and understand a binding legal contract, you are not a minor in the jurisdiction in which you reside  and have the full right, power, and authority to enter into and comply with the terms and conditions of this Agreement on behalf of yourself and any company or legal entity for which you may access or use the App. You further represent that you are not a citizen, resident, or member of any jurisdiction or group that is subject to economic sanctions or where your use of the App would be illegal or otherwise violate any applicable law. You further represent that your access and use of the App will fully comply with all applicable laws and regulations and that you will not access or use the Interface to conduct, promote, or otherwise facilitate any illegal activity.</p>
						</div>
						<div className="terms_titles">
							<h3>DESCRIPTION OF SERVICE </h3>
							<p>Cashero is a secure mobile-based application that provides a secure platform for high-yield savings, multi-currency wallets, and instant, fee-free internal and cross-border payments. Cashero allows users to deposit GBP, EUR, and USD to generate interest. Interest is generated by converting deposited GBP, EUR, and USD into a basket of cryptocurrency stablecoins i.e. DAI and USDC, which are invested into decentralized protocols on Ethereum and other blockchains that allow suppliers and borrowers of certain digital assets to participate in autonomous interest rate markets (the “Protocols”).  This is done by Cashero Investment OÜ. Interest is also generated by lending GBP and EUR as collateralized loans to businesses under Cashero Financial OÜ. Users can withdraw their deposits and interest from Cashero in GBP, EUR, USD, or their local currency. </p>
							<p>Cashero does not provide a cryptocurrency exchange service and does not allow cryptocurrency deposits. </p>
							<p>Cashero has established two companies to separate elements of the business. Cashero Financial OÜ for traditional financial transactions and Cashero Investment OÜ for those that involve virtual currencies. Cashero Financial OÜ will hold the financial institution license and Cashero Investment OÜ will hold the virtual currency service license. </p>
							<p>Cashero Financial OÜ uses Sum And Substance Ltd a KYC, KYB and AML service provider (Data protection No. ZA222205); Cashero Investment OÜ a Virtual Currency Services provider (license No. XXXX); </p>
						</div>
						<div className="terms_titles">
							<h3>CONSENT</h3>
							<p>BY DEPOSITING YOUR FUNDS (GBP, EUR, OR USD)  TO THE APP, YOU FULLY UNDERSTAND AND CONSENT FOR CASHERO TO CONVERT YOUR DEPOSITED FUNDS (GBP, EUR, OR USD) TO CRYPTOCURRENCY STABLECOINS WHICH WILL BE INVESTED INTO DECENTRALIZED FINANCE LENDING PROTOCOLS AND DECENTRALIZED FINANCE MONEY MARKET PROTOCOLS.  YOU ALSO CONSENT TO PLACE YOUR FUNDS IN COLLATERALIZED DEPOSITS TO GENERATE YIELD. </p>
						</div>
						<div className="terms_titles">
							<h3>INTELLECTUAL PROPERTY RIGHTS</h3>
							<p>Unless otherwise indicated, the App is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the App (collectively, the “Content”) and the trademarks, service marks, and logos contained therein (the “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws, international copyright laws, and international conventions. The Content and the Marks are provided on the App “AS IS” for your information and personal use only. Except as expressly provided in these Terms, no part of the App and no content or marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission. </p>
							<p>Provided that you are eligible to use the App, you are granted a limited license to access and use the App and to download or print a copy of any portion of the content to which you have properly gained access solely for your personal, non-commercial use. We reserve all rights not expressly granted to you in and to the App, the content, and the marks.</p>
						</div>
						<div className="terms_titles">
							<h3>USER REPRESENTATIONS</h3>
							<p>By using the App, you hereby confirm you are fully aware, agree, represent, and warrant that: </p>
							<p>1) All registration information you submit will be true, accurate, current, and complete; </p>
							<p>2) You will maintain the accuracy of such information and promptly update such registration information as necessary; </p>
							<p>3) You have the legal capacity and you agree to comply with these Terms; </p>
							<p>4) You are of legal age and capabilities to form and understand a binding legal contract;</p>
							<p>5) You are not a minor in the jurisdiction in which you reside;</p>
							<p>6) You have not been banned or restricted previously from using the App;</p>
							<p>7) You will not access the App through automated or non-human means, whether through a bot, script, or otherwise; </p>
							<p>8) You will not use the App for any illegal or unauthorized purpose; and </p>
							<p>9) Your use of the App will not violate any applicable law or regulation.</p>
							<br />
							<p>If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the App (or any portion thereof). </p>
						</div>
						<div className="terms_titles">
							<h3>USER REGISTRATION </h3>
							<p>You will be required to register and verify yourself to use the services provided by Cashero. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable. </p>
							<p>When registering to use the App you are committed to providing any requested information as per our AML/KYC policy and AML/KYC agreement. Additionally, you take full responsibility for all activities that occur under your account and accept all risks of any authorized or unauthorized access to your account, to the maximum extent permitted by law. You also declare all information provided is accurate and truthful. During the registration and verification process, you may be required to provide your personal information to us, including but not limited to, name, date of birth, address, citizenship, occupation, name, and date of issuance document used for identification, name, and the number of the document used for identification and verification of the identity of a foreign legal person, e-mail, telephone number, contact person and email, etc.</p>
						</div>
						<div className="terms_titles">
							<h3>USER CONTENT</h3>
							<p>You may post, upload, input, provide, or submit personal data and information to us, including but not limited to, name, email address, phone number, IP address, text, code, or other information and materials, sign up for our mailing list, or create an account on our App (hereinafter collectively “User Content”), as a customer you must ensure that the User Content provided at that or at any other time is true, accurate, current, and complete; and any User Content that is post, upload, input, provide, or submit to us or our App does not breach or infringe the intellectual property rights of any third-party.</p>
							<p>The App does not own, control, or endorse any User Content transmitted, stored, or processed via the App or provided in any other way by the customers, and the App is not responsible or liable for any User Content. You agree to not hold the App or any of its employees, directors, partners, third-party providers accountable nor liable in any way to the User Content. You are solely responsible and liable for all your User Content and use of any interactive features, links, information, or content on the Company Websites. The Customer represents and warrants that (i) you own all intellectual property rights (or have obtained all necessary permissions) to provide User Content and to grant licenses in these Terms; (ii) User Content does not violate any agreements or confidentiality obligations; and (iii) User Content does not violate, infringe, or misappropriate any intellectual property rights or other proprietary rights, including the right of publicity or privacy, of any person or entity.</p>
							<p>You, the Customer are solely responsible for maintaining the confidentiality of your User Content and any of your non-public information. Furthermore, you are completely responsible for any and all activities (if any) that occur under your account. You must notify us immediately of any unauthorized use of your User Content, account, or any other breach of security. We are not liable for any losses or damages that you may incur as a result of someone else using your User Content or account, either with or without your knowledge. However, you may be held liable for losses incurred by The Company Parties or another party, due to someone else using your User Content or account. You may not use anyone else’s User Content or account at any time without permission from such person or entity.</p>
							<p>By posting, uploading, inputting, providing, or submitting your User Content to us, you grant The Company, its affiliates, and any necessary sub-licensees, a non-exclusive, worldwide, perpetual right and permission to use, reproduce, copy, edit, modify, translate, reformat, create derivative works from, distribute, transmit, publicly perform, and publicly display your User Content and sub-license such rights to others.</p>
							<p>You must immediately update and inform us of any changes to your User Content by updating your personal data. Contact us, for us to communicate with you effectively and provide accurate and current information. Although we have no obligation to screen, edit, or monitor User Content, we reserve the right and have absolute discretion to remove, screen, or edit User Content. Furthermore, if we have reason to believe that there is likely to be a breach of security, misuse of our App, or any breach of your obligations under these terms or the Privacy Policy, we may suspend your use of the App at any time and for any reason. Any User Content submitted by you for our App may be accessed by us globally.</p>
						</div>
						<div className="terms_titles">
							<h3>PROHIBITED ACTIVITIES</h3>
							<p>You may not access or use the App for any purpose other than that for which we make the App available. The App may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.</p>
							<p>As a user of the Site, you agree not to:</p>
							<p>1) Systematically retrieve data or other content from the App to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us;</p>
							<p>2) Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords;</p>
							<p>3) Circumvent, disable, or otherwise interfere with security-related features of the App, including features that prevent or restrict the use or copying of any content or enforce limitations on the use of the App and/or the content contained therein;</p>
							<p>4) Disparage, tarnish, or otherwise harm, in our opinion, us and/or the App;</p>
							<p>5) Use any information obtained from the App in order to harass, abuse, or harm another person;</p>
							<p>6) Make improper use of our support services or submit false reports of abuse or misconduct;</p>
							<p>7) Use the App in a manner inconsistent with any applicable laws or regulations;</p>
							<p>8) Use the App to advertise or offer to sell goods and services;</p>
							<p>9) Engage in unauthorized framing of or linking to the App;</p>
							<p>10) Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the App or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the App;</p>
							<p>11) Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools;</p>
							<p>12)	Delete the copyright or other proprietary rights notice from any content;</p>
							<p>13)	Attempt to impersonate another user or person or use the username of another user;</p>
							<p>14)	Sell or otherwise transfer your profile;</p>
							<p>15)	Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”) 1x1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”);</p>
							<p>16)	Interfere with, disrupt, or create an undue burden on the App or the networks or services connected to the App;</p>
							<p>17)	Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the App to you;</p>
							<p>18)	Attempt to bypass any measures of the App designed to prevent or restrict access to the App, or any portion of the App;</p>
							<p>19)	Copy or adapt the App’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code;</p>
							<p>20)	Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the App;</p>
							<p>21)	Except as may be the result of a standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the App, or using or launching any unauthorized script or other software; </p>
							<p>22)	Make any unauthorized use of the App, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses;</p>
							<p>23)	Use the App as part of any effort to compete with us or otherwise use the App and/or the content for any revenue-generating endeavor or commercial enterprise.</p>
						</div>
						<div className="terms_titles">
							<h3>NO PROFESSIONAL ADVICE</h3>
							<p>All information provided by the App is for informational purposes only and should not be construed as professional advice. You should not take, or refrain from taking, any action based on any information contained in the App. Before you make any financial, legal, or other decisions involving the Interface, you should seek independent professional advice from an individual who is licensed and qualified in the area for which such advice would be appropriate.</p>
						</div>
						<div className="terms_titles">
							<h3>CONTRIBUTION LICENSE</h3>
							<p>You and the App agree that we may access, store, process, and use any information and personal data that you provide following the terms of the Privacy Policy and your choices (including settings).</p>
							<p>By submitting suggestions or other feedback regarding the App, you agree that we can use and share such feedback for any purpose without compensation to you. </p>
							<p>We do not assert any ownership over your contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the App. You are solely responsible for your contributions to the App and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your contributions. </p>
						</div>
						<div className="terms_titles">
							<h3>THIRD-PARTY WEBSITE AND CONTENT</h3>
							<p>The App may contain (or you may be sent via the App) links to other third-party websites (“Third-Party Websites”) as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, information, applications, software, and other content or items belonging to or originating from third parties (“Third-Party Content”). Such Third-Party Websites and Third-Party Content are not investigated, monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the App or any Third-Party content posted on, available through, or installed from the App, including the content, accuracy, offensiveness, opinions, reliability, privacy practices, or other policies of or contained in the Third-Party Websites or the Third-Party Content. Inclusion of linking to, or permitting the use or installation of any Third-Party Websites or any Third-Party Content does not imply approval or endorsement thereof by us. If you decide to leave the App and access Third-Party Websites or to use or install any Third-Party Content, you do so at your own risk, and you should be aware these Terms no longer govern. You should review the applicable terms and policies, including privacy and data gathering practices, of any website to which you navigate from the App or relating to any applications you use or install from the App. Any purchases you make through Third-Party Websites will be through other websites and from other companies, and we take no responsibility whatsoever in relation to such purchases which are exclusively between you and the applicable third party. You agree and acknowledge that we do not endorse the products or services offered on Third-Party Websites and you shall hold us harmless from any harm caused by your purchase of such products or services. Additionally, you shall hold us harmless from any losses sustained by you or harm caused to you relating to or resulting in any way from any Third-Party Content or any contact with Third-Party Websites. </p>
						</div>
						<div className="terms_titles">
							<h3>APP MANAGEMENT</h3>
							<p>We reserve the right, but no obligation, to:</p>
							<p>1)	Monitor the APP for violations of these Terms; </p>
							<p>2)	Take appropriate legal action against anyone who, in our sole discretion, violates the law or these Terms, including without limitation, reporting such user to law enforcement authorities; </p>
							<p>3)	In our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your contributions or any portion thereof; </p>
							<p>4)	In our sole discretion and without limitation, notice, or liability, to remove from the APP or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and </p>
							<p>5)	Otherwise manage the App in a manner designed to protect our rights and property and to facilitate the proper functioning of the App. </p>
						</div>
						<div className="terms_titles">
							<h3>PRIVACY POLICY</h3>
							<p>We care about data privacy and security. Please refer to our <Link link="/privacy-policy">Privacy Policy</Link>.</p>
						</div>
						<div className="terms_titles">
							<h3>TERM AND TERMINATION</h3>
							<p>These Terms shall remain in full force and effect while you use the App. Without limiting any other provision of these Terms, we reserve the right to, in our sole discretion and without notice or liability, deny access to and use of the App (including blocking certain IP addresses), to any person for any reason for no reason, including without limitation for breach of any representation, warranty, or covenant contained in these Terms or of any applicable law or regulation. We may terminate your use or participation in the App or delete your account and any content or information that you posted at any time, without warning, at our sole discretion. </p>
							<p>If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress. </p>
						</div>
						<div className="terms_titles">
							<h3>MODIFICATIONS AND INTERRUPTIONS</h3>
							<p>We reserve the right to change, modify, or remove the contents of the App at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our App. We also reserve the right to modify or discontinue all or part of the App without notice at any time. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the App. </p>
							<p>We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the App at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the App during any downtime or discontinuance of the App. </p>
						</div>
						<div className="terms_titles">
							<h3>FORCE MAJEURE</h3>
							<p>Force Majeure is the event where circumstances are beyond our control, including but not limited to, electricity blackouts, natural disasters, cyber-attacks, war, strike, riot, crime, epidemic or any other event that is beyond the App’s reasonable abilities to control (hereinafter “Force Majeure”) the App may experience delays or failure to deliver the Services. In such a case you agree to not hold the App accountable for any delays in Services, loss of Transactions, or loss of funds.</p>
						</div>
						<div className="terms_titles">
							<h3>INDEMNIFICATION AND LIABILITIES</h3>
							<p>Except if otherwise required by law, or the regulation under which we operate, in no other event the App, our directors, employees, partners, third-party providers, be liable to any or all damages, including but not limited to, suspension of funds on customer account in our App or any other external accounts, mistakes in data, loss of data, loss of information, errors, unauthorized access to our records, interruptions, loss of files, defects, viruses, occurring directly, indirectly, or otherwise arising as a result of using our services or inability of using our services on our App, to the maximum extent allowed by laws of the applicable jurisdiction. You agree to indemnify and not hold the App, our directors, employees, partners, third-party providers accountable for any claim, demand, action, damage, loss, cost, or expense, including but not limited to, attorneys’ fees, arising out or relating to the use of our Services and the App.</p>
						</div>
						<div className="terms_titles">
							<h3>ASSUMPTION OF RISK </h3>
							<p>By accessing and using the App, you represent that you understand the inherent risks associated with using cryptographic and blockchain-based systems, decentralized protocols, and that you have a working knowledge of the usage and intricacies of digital assets such as cryptocurrency stablecoins i.e. DAI and USDC, and other digital tokens. <b> Accordingly, you understand and agree to assume full responsibility for all of the risks of accessing and using the App.</b> </p>
						</div>
						<div className="terms_titles">
							<h3>GOVERNING LAW AND DISPUTES</h3>
							<p>These Terms and any non-contractual obligation arising out of or in connection with these Terms shall be governed by the laws of the Republic of Estonia. Any dispute, controversy, or claim arising out of these Terms or any non-contractual obligation arising out of or in connection with these Terms shall be resolved through direct negotiations between the Cashero and the customer or if the parties are unable to resolve the dispute through negotiations, then the dispute shall be settled in Harju County Court pursuant to the laws of the Republic of Estonia. If your habitual residence is in the EU, and you are a consumer, you additionally possess the protection provided to you by the obligatory provision of the law or your country of residence. </p>
						</div>
						<div className="terms_titles">
							<h3>CORRECTIONS</h3>
							<p>There may be information on the App that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information. We reserve the right to correct any error, inaccuracies, or omissions and to change or update the information on the App at any time, without prior notice. </p>
						</div>
						<div className="terms_titles">
							<h3>DISCLAIMER</h3>
							<p>The App is provided on an as-is and as-available basis. You agree that your use of the App and our services will be at your sole risk. To the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the App and your use thereof, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We make no warranties or representations about the accuracy or completeness of the App’s content or the content of any websites linked to the App and we will assume no liability or responsibility for any 1) errors, mistakes, or inaccuracies of content and materials, 2) any authorized access to or use of our secure servers and/or financial information stored therein, 3) any interruption or cessation of transmission to or from the App 4) any bugs, viruses, trojan horses, or the like which may be transmitted to or through the App by any third party, and/or 6) any errors or omissions in any content and materials or for any loss or damage of any content and materials or for any loss or damage of any kind incurred as a result of the use of any content posted, transmitted, or otherwise made available via the App. We do not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by a third party through the App, any hyperlinked website, or any website or mobile application featured in any banner or other advertising, and we will not be a party to or in any way responsible for monitoring any transaction between you and any third-party providers of products or services. As with the purchase of a product or service through any medium or in any environment, you should use your best judgment and exercise caution where appropriate.  </p>
						</div>
						<div className="terms_titles">
							<h3>CASHERO'S GOLDEN TICKET FREE DRAW! </h3>
							<ul className="condition-list">
								<li>Every 3 days one lucky Cashero user will win $1000! For every friend that you refer that wins the $1000 prize, you will get a referral bonus of $100 into your wallet because you invited them to Cashero.</li>
								<li>Cashero will select a winner at random every 3 days from the pool of Golden Ticket entries. This will be done at Cashero’s sole discretion, from all eligible participants. You can win more than once.</li>
								<li>You will be able to withdraw your funds (and the interest you’ve accrued) once Cashero is live. At that point you must go through KYC, our Know Your Customer identity verification just to make sure you are who you say you are. Prize money can only be withdrawn and cannot be sent to other users as a payment.</li>
								<li>We may, at our sole discretion, suspend, terminate or change the terms and requirements of the Cashero Golden Ticket Giveaway.</li>
								<li>Details of how to enter form part of the terms and conditions. It is a condition of entry that all rules are accepted as final and that the entrant agrees to abide by these rules. The decision of Cashero as promotion administrator is final and no correspondence will be entered into.</li>
								<li>These terms are published in English and any translation is a courtesy and office translation only - participants of the Cashero Golden Ticket Giveaway cannot derive any rights from the translated version. The English language version of these terms shall apply and prevail and be conclusive and binding. The English version shall be used in legal proceedings.</li>
								<li>To the extent permitted by law, these Cashero Golden Ticket Giveaway terms shall be exclusively governed by and construed in accordance with the laws of England and Wales. Any disputes arising out or in connection with these terms shall exclusively be submitted to and dealt with by the competent court in London, England.</li>
								<li>The Cashero Golden Ticket Giveaway is organised by Romans 828 (UK) Limited trading as "Cashero" is a limited company registered in England and Wales. Registered number: 12783127. Registered office: 33 St James's Square, London, SW1Y 4JS, United Kingdom.</li>
								<li><a href="https://www.gamblingcommission.gov.uk/for-the-public/Safer-gambling/Consumer-guides/Running-prize-competitions-and-free-draws.aspx ">https://www.gamblingcommission.gov.uk/for-the-public/Safer-gambling/Consumer-guides/Running-prize-competitions-and-free-draws.aspx </a></li>
							</ul>
						</div>
						<div className="terms_titles">
							<h3>CONTACT US</h3>
							<p>In order to resolve a complaint regarding the App or to receive further information regarding the use of the App, please contact us. </p>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}