const API = process.env.REACT_APP_API_URL
  ? process.env.REACT_APP_API_URL
  : "https://development-spot.cashero.com";
//testing: "https://testing-spot.cashero.com"
//development: "https://development-spot.cashero.com"
//production: "https://spot.cashero.com"

const firebaseAPI =
  "https://firestore.googleapis.com/v1/projects/cashero-development-76cca/databases/(default)/documents/";
//testing: "https://firestore.googleapis.com/v1/projects/cashero-testing-54a48/databases/(default)/documents/"
//production: "https://firestore.googleapis.com/v1/projects/cashero-828/databases/(default)/documents/"
//development: "https://firestore.googleapis.com/v1/projects/cashero-development-76cca/databases/(default)/documents/"

export const websiteLink = "https://www.cashero.com";

export const wordPressLink = "http://34.72.26.38:8005";
//testing: "http://130.211.200.187:8005"
//development: "http://34.72.26.38:8005"
//production: "https://wp.cashero.com"

export const androidAppLink = "https://play.google.com/store/apps/details?id=com.rns.casheroapp";

export const iosAppLink = "https://apps.apple.com/us/app/cashero/id1547603420";

export const recaptchaSiteKep = "6Lc5YbQaAAAAAJRSNLyM9ZXpbvweEgr3bRzdbMaB";

export const ipAPI = "https://ipwhois.app/json/";

export const gtmId = "GTM-KKSRK7H";
//testing/development:   GTM-KKSRK7H
//production: GTM-MBGVT62

export const EndPoints = {
  preregistration: `${API + "/api/users/preregistration"}`,
  contactUs: `${API + "/api/contactUs"}`,
  joinWaitlist: `${API + "/api/users/waitingregistration"}`,
};

const firebaseTableName = {
  ExchangeRates: "ExchageRates",
};

export const FirebaseEndPoints = {
  ExchangeRates: `${firebaseAPI + `${firebaseTableName.ExchangeRates}/BR`}`,
  IndividualExchangeRates: `${firebaseAPI + firebaseTableName.ExchangeRates}`,
};

export const counrtrylist = [
  {
    name: "Afghanistan",
    name_br: "Afeganistão",
    name_mx: "Afganistán",
    name_ar: "Afganistán",
    name_cl: "Afganistán",
    name_fr: "Afghanistan",
    name_gr: "Afghanistan",
    name_it: "Afghanistan",
    name_pt: "Afeganistão",
    name_za: "Afeganistão",
    name_in: "Afghanistan",
    name_id: "Afganistan",
    name_ph: "Afghanistan",
    name_sg: "Afghanistan",
    name_es: "Afganistán",
    flag: "🇦🇫",
    code: "AF",
    dial_code: "+93",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Åland Islands",
    name_br: "Ilhas Aland",
    name_mx: "Islas Aland",
    name_ar: "Islas Aland",
    name_cl: "Islas Aland",
    name_fr: "Iles Aland",
    name_gr: "Ålandinseln",
    name_it: "Isole Aland",
    name_pt: "Ilhas Aland",
    name_za: "Åland-eilande",
    name_in: "Åland Islands",
    name_id: "Pulau Aland",
    name_ph: "Åland Islands",
    name_sg: "Åland Islands",
    name_es: "Islas Aland",
    flag: "🇦🇽",
    code: "AX",
    dial_code: "+358",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Albania",
    name_br: "Albânia",
    name_mx: "Albânia",
    name_ar: "Albânia",
    name_cl: "Albânia",
    name_fr: "Albanie",
    name_gr: "Albanien",
    name_it: "Albania",
    name_pt: "Albânia",
    name_za: "Albanië",
    name_in: "Albania",
    name_id: "Albania",
    name_ph: "Albania",
    name_sg: "Albania",
    name_es: "Albânia",
    flag: "🇦🇱",
    code: "AL",
    dial_code: "+355",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Algeria",
    name_br: "Argélia",
    name_mx: "Argelia",
    name_ar: "Argelia",
    name_cl: "Argelia",
    name_fr: "Algérie",
    name_gr: "Algerien",
    name_it: "Algeria",
    name_pt: "Argélia",
    name_za: "Algerië",
    name_in: "Afghanistan",
    name_id: "Aljazair",
    name_ph: "Algeria",
    name_sg: "Afghanistan",
    name_es: "Argelia",
    flag: "🇩🇿",
    code: "DZ",
    dial_code: "+213",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "American Samoa",
    name_br: "Samoa Americana",
    name_mx: "Samoa Americana",
    name_ar: "Samoa Americana",
    name_cl: "Samoa Americana",
    name_fr: "Samoa américaines",
    name_gr: "Amerikanischen Samoa-Inseln",
    name_it: "Samoa americane",
    name_pt: "Samoa Americana",
    name_za: "Amerikaanse Samoa",
    name_in: "American Samoa",
    name_id: "Samoa Amerika",
    name_ph: "American Samoa",
    name_sg: "American Samoa",
    name_es: "Samoa Americana",
    flag: "🇦🇸",
    code: "AS",
    dial_code: "+1684",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Andorra",
    name_br: "Andorra",
    name_mx: "Andorra",
    name_ar: "Andorra",
    name_cl: "Andorra",
    name_fr: "Andorre",
    name_gr: "Andorra",
    name_it: "Andorra",
    name_pt: "Andorra",
    name_za: "Andorra",
    name_in: "Andorra",
    name_id: "Andora",
    name_ph: "Andorra",
    name_sg: "Albania",
    name_es: "Andorra",
    flag: "🇦🇩",
    code: "AD",
    dial_code: "+376",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Angola",
    name_br: "Angola",
    name_mx: "Angola",
    name_ar: "Angola",
    name_cl: "Angola",
    name_fr: "Angola",
    name_gr: "Angola",
    name_it: "Angola",
    name_pt: "Angola",
    name_za: "Angola",
    name_in: "Angola",
    name_id: "Angola",
    name_ph: "Angola",
    name_sg: "Angola",
    name_es: "Angola",
    flag: "🇦🇴",
    code: "AO",
    dial_code: "+244",
    phone_length: 11,
    white_listed: true,
  },
  {
    name: "Anguilla",
    name_br: "Anguilla",
    name_mx: "Anguila",
    name_ar: "Anguila",
    name_cl: "Anguila",
    name_fr: "Anguilla",
    name_gr: "Anguilla",
    name_it: "Anguilla",
    name_pt: "Anguilla",
    name_za: "Anguilla",
    name_in: "Anguilla",
    name_id: "Anguila",
    name_ph: "Anguilla",
    name_sg: "Angola",
    name_es: "Anguila",
    flag: "🇦🇮",
    code: "AI",
    dial_code: "+1264",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Antarctica",
    name_br: "Antártica",
    name_mx: "Antártida",
    name_ar: "Antártida",
    name_cl: "Antártida",
    name_fr: "Antarctique",
    name_gr: "Antarktis",
    name_it: "Antartide",
    name_pt: "Antártica",
    name_za: "Antarktika",
    name_in: "Antarctica",
    name_id: "Antartika",
    name_ph: "Antarctica",
    name_sg: "Antarctica",
    name_es: "Antártida",
    flag: "🇦🇶",
    code: "AQ",
    dial_code: "+672",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Antigua and Barbuda",
    name_br: "Antigua e Barbuda",
    name_mx: "Antigua y Barbuda",
    name_ar: "Antigua y Barbuda",
    name_cl: "Antigua y Barbuda",
    name_fr: "Antigua-et-Barbuda",
    name_gr: "Antigua und Barbuda",
    name_it: "Antigua e Barbuda",
    name_pt: "Antigua e Barbuda",
    name_za: "Engels na suid",
    name_in: "Antigua and Barbuda",
    name_id: "Antigua dan Barbuda",
    name_ph: "Antigua at Barbuda",
    name_sg: "Antarctica",
    name_es: "Antigua y Barbuda",
    flag: "🇦🇬",
    code: "AG",
    dial_code: "+1268",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Argentina",
    name_br: "Argentino",
    name_mx: "Argentina",
    name_ar: "Argentina",
    name_cl: "Argentina",
    name_fr: "Argentine",
    name_gr: "Argentinien",
    name_it: "Argentina",
    name_pt: "Argentino",
    name_za: "Argentinië",
    name_in: "Argentina",
    name_id: "Argentina",
    name_ph: "Argentina",
    name_sg: "Argentina",
    name_es: "Argentina",
    flag: "🇦🇷",
    code: "AR",
    dial_code: "+54",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Armenia",
    name_br: "Armênia",
    name_mx: "Armenia",
    name_ar: "Armenia",
    name_cl: "Armenia",
    name_fr: "Arménie",
    name_gr: "Armenien",
    name_it: "Armenia",
    name_pt: "Armênia",
    name_za: "Armenië",
    name_in: "Armenia",
    name_id: "Armenia",
    name_ph: "Armenia",
    name_sg: "Armenia",
    name_es: "Armenia",
    flag: "🇦🇲",
    code: "AM",
    dial_code: "+374",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Aruba",
    name_br: "Aruba",
    name_mx: "Aruba",
    name_ar: "Aruba",
    name_cl: "Aruba",
    name_fr: "Aruba",
    name_gr: "Aruba",
    name_it: "Aruba",
    name_pt: "Aruba",
    name_za: "Aruba",
    name_in: "Aruba",
    name_id: "Aruba",
    name_ph: "Aruba",
    name_sg: "Aruba",
    name_es: "Aruba",
    flag: "🇦🇼",
    code: "AW",
    dial_code: "+297",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Australia",
    name_br: "Austrália",
    name_mx: "Australia",
    name_ar: "Australia",
    name_cl: "Australia",
    name_fr: "Australie",
    name_gr: "Australien",
    name_it: "Australia",
    name_pt: "Austrália",
    name_za: "Australië",
    name_in: "Australia",
    name_id: "Australia",
    name_ph: "Australia",
    name_sg: "Australia",
    name_es: "Australia",
    flag: "🇦🇺",
    code: "AU",
    dial_code: "+61",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Austria",
    name_br: "Áustria",
    name_mx: "Austria",
    name_ar: "Austria",
    name_cl: "Austria",
    name_fr: "L'Autriche",
    name_gr: "Österreich",
    name_it: "Austria",
    name_pt: "Áustria",
    name_za: "Oostenryk",
    name_in: "Austria",
    name_id: "Austria",
    name_ph: "Austria",
    name_sg: "Austria",
    name_es: "Austria",
    flag: "🇦🇹",
    code: "AT",
    dial_code: "+43",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Azerbaijan",
    name_br: "Azerbaijão",
    name_mx: "Azerbaiyán",
    name_ar: "Azerbaiyán",
    name_cl: "Azerbaiyán",
    name_fr: "Azerbaïdjan",
    name_gr: "Aserbaidschan",
    name_it: "Azerbaigian",
    name_pt: "Azerbaijão",
    name_za: "Azerbeidjan",
    name_in: "Azerbaijan",
    name_id: "Azerbaijan",
    name_ph: "Azerbaijan",
    name_sg: "Azerbaijan",
    name_es: "Azerbaiyán",
    flag: "🇦🇿",
    code: "AZ",
    dial_code: "+994",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Bahamas",
    name_br: "Bahamas",
    name_mx: "Bahamas",
    name_ar: "Bahamas",
    name_cl: "Bahamas",
    name_fr: "Bahamas",
    name_gr: "Bahamas",
    name_it: "Bahamas",
    name_pt: "Bahamas",
    name_za: "Bahamas",
    name_in: "Bahamas",
    name_id: "Bahama",
    name_ph: "Bahamas",
    name_sg: "Bahamas",
    name_es: "Bahamas",
    flag: "🇧🇸",
    code: "BS",
    dial_code: "+1242",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Bahrain",
    name_br: "Bahrain",
    name_mx: "Bahréin",
    name_ar: "Bahréin",
    name_cl: "Bahréin",
    name_fr: "Bahreïn",
    name_gr: "Bahrain",
    name_it: "Bahrein",
    name_pt: "Bahrain",
    name_za: "Bahrein",
    name_in: "Bahrain",
    name_id: "Bahrain",
    name_ph: "Bahrain",
    name_sg: "Bahrain",
    name_es: "Bahréin",
    flag: "🇧🇭",
    code: "BH",
    dial_code: "+973",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Bangladesh",
    name_br: "Bangladesh",
    name_mx: "Bangladesh",
    name_ar: "Bangladesh",
    name_cl: "Bangladesh",
    name_fr: "Bangladesh",
    name_gr: "Bangladesch",
    name_it: "Bangladesh",
    name_pt: "Bangladesh",
    name_za: "Bangladesj",
    name_in: "Bangladesh",
    name_id: "Bangladesh",
    name_ph: "Bangladesh",
    name_sg: "Bangladesh",
    name_es: "Bangladesh",
    flag: "🇧🇩",
    code: "BD",
    dial_code: "+880",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Barbados",
    name_br: "Barbadas",
    name_mx: "Barbados",
    name_ar: "Barbados",
    name_cl: "Barbados",
    name_fr: "Barbade",
    name_gr: "Barbados",
    name_it: "Barbados",
    name_pt: "Barbadas",
    name_za: "Barbados",
    name_in: "Barbados",
    name_id: "Barbados",
    name_ph: "Barbados",
    name_sg: "Barbados",
    name_es: "Barbados",
    flag: "🇧🇧",
    code: "BB",
    dial_code: "+1246",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Belarus",
    name_br: "Bielo-Rússia",
    name_mx: "Bielorrusia",
    name_ar: "Bielorrusia",
    name_cl: "Bielorrusia",
    name_fr: "Biélorussie",
    name_gr: "Weißrussland",
    name_it: "Bielorussia",
    name_pt: "Bielo-Rússia",
    name_za: "Wit-Rusland",
    name_in: "Belarus",
    name_id: "Belarusia",
    name_ph: "Belarus",
    name_sg: "Belarus",
    name_es: "Bielorrusia",
    flag: "🇧🇾",
    code: "BY",
    dial_code: "+375",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Belgium",
    name_br: "Bélgica",
    name_mx: "Bélgica",
    name_ar: "Bélgica",
    name_cl: "Bélgica",
    name_fr: "Belgique",
    name_gr: "Belgien",
    name_it: "Belgio",
    name_pt: "Bélgica",
    name_za: "België",
    name_in: "Belgium",
    name_id: "Belgium",
    name_ph: "Belgium",
    name_sg: "Belgium",
    name_es: "Bélgica",
    flag: "🇧🇪",
    code: "BE",
    dial_code: "+32",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Belize",
    name_br: "Belize",
    name_mx: "Belize",
    name_ar: "Belize",
    name_cl: "Belize",
    name_fr: "Belize",
    name_gr: "Belize",
    name_it: "Belize",
    name_pt: "Belize",
    name_za: "Belize",
    name_in: "Belize",
    name_id: "Belize",
    name_ph: "Belize",
    name_sg: "Belize",
    name_es: "Belize",
    flag: "🇧🇿",
    code: "BZ",
    dial_code: "+501",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Benin",
    name_br: "Benin",
    name_mx: "Benin",
    name_ar: "Benin",
    name_cl: "Benin",
    name_fr: "Bénigne",
    name_gr: "Benin",
    name_it: "Benin",
    name_pt: "Benin",
    name_za: "Benin",
    name_in: "Benin",
    name_id: "Benin",
    name_ph: "Benin",
    name_sg: "Benin",
    name_es: "Benin",
    flag: "🇧🇯",
    code: "BJ",
    dial_code: "+229",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Bermuda",
    name_br: "Bermudas",
    name_mx: "islas Bermudas",
    name_ar: "islas Bermudas",
    name_cl: "islas Bermudas",
    name_fr: "Bermudes",
    name_gr: "Bermuda",
    name_it: "Bermuda",
    name_pt: "Bermudas",
    name_za: "Bermuda",
    name_in: "Bermuda",
    name_id: "Bermuda",
    name_ph: "Bermuda",
    name_sg: "Bermuda",
    name_es: "islas Bermudas",
    flag: "🇧🇲",
    code: "BM",
    dial_code: "+1441",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Bhutan",
    name_br: "Butão",
    name_mx: "Bután",
    name_ar: "Bután",
    name_cl: "Bután",
    name_fr: "Bhoutan",
    name_gr: "Bhutan",
    name_it: "Bhutan",
    name_pt: "Butão",
    name_za: "Bhutan",
    name_in: "Bhutan",
    name_id: "Bhutan",
    name_ph: "Bhutan",
    name_sg: "Bhutan",
    name_es: "Bután",
    flag: "🇧🇹",
    code: "BT",
    dial_code: "+975",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Bolivia, Plurinational State of bolivia",
    name_br: "Bolívia, Estado Plurinacional da Bolívia",
    name_mx: "Bolivia, Estado Plurinacional de bolivia",
    name_ar: "Bolivia, Estado Plurinacional de bolivia",
    name_cl: "Bolivia, Estado Plurinacional de bolivia",
    name_fr: "Bolivie, État plurinational de bolivie",
    name_gr: "Bolivien, Plurinationaler Staat Bolivien",
    name_it: "Bolivia, Stato Plurinazionale della Bolivia",
    name_pt: "Bolívia, Estado Plurinacional da Bolívia",
    name_za: "Bolivia, die meervoudige staat Bolivia",
    name_in: "Bolivia, Plurinational State of bolivia",
    name_id: "Bolivia, Negara Plurinasional bolivia",
    name_ph: "Bolivia, Plurinational State ng bolivia",
    name_sg: "Bolivia, Plurinational State of bolivia",
    name_es: "Bolivia, Estado Plurinacional de bolivia",
    flag: "🇧🇴",
    code: "BO",
    dial_code: "+591",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Bosnia and Herzegovina",
    name_br: "Bolívia, Estado Plurinacional da Bolívia",
    name_mx: "Bolivia, Estado Plurinacional de bolivia",
    name_ar: "Bolivia, Estado Plurinacional de bolivia",
    name_cl: "Bolivia, Estado Plurinacional de bolivia",
    name_fr: "Bolivie, État plurinational de bolivie",
    name_gr: "Bolivien, Plurinationaler Staat Bolivien",
    name_it: "Bolivia, Stato Plurinazionale della Bolivia",
    name_pt: "Bolívia, Estado Plurinacional da Bolívia",
    name_za: "Bolivia, die meervoudige staat Bolivia",
    name_in: "Bosnia and Herzegovina",
    name_id: "Bolivia, Negara Plurinasional bolivia",
    name_ph: "Bolivia, Plurinational State ng bolivia",
    name_sg: "Bosnia and Herzegovina",
    name_es: "Bolivia, Estado Plurinacional de bolivia",
    flag: "🇧🇦",
    code: "BA",
    dial_code: "+387",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Botswana",
    name_br: "Botswana",
    name_mx: "Botswana",
    name_ar: "Botswana",
    name_cl: "Botswana",
    name_fr: "Botswana",
    name_gr: "Botswana",
    name_it: "Botswana",
    name_pt: "Botswana",
    name_za: "Botswana",
    name_in: "Botswana",
    name_id: "Botswana",
    name_ph: "Botswana",
    name_sg: "Botswana",
    name_es: "Botswana",
    flag: "🇧🇼",
    code: "BW",
    dial_code: "+267",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Bouvet Island",
    name_br: "Ilha Bouvet",
    name_mx: "Isla Bouvet",
    name_ar: "Isla Bouvet",
    name_cl: "Isla Bouvet",
    name_fr: "Île Bouvet",
    name_gr: "Bouvet-Insel",
    name_it: "Isola Bouvet",
    name_pt: "Ilha Bouvet",
    name_za: "Bouvet-eiland",
    name_in: "Bouvet Island",
    name_id: "Pulau Bouvet",
    name_ph: "Bouvet Island",
    name_sg: "Bouvet Island",
    name_es: "Isla Bouvet",
    flag: "🇧🇻",
    code: "BV",
    dial_code: "+47",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Brazil",
    name_br: "Brasil",
    name_mx: "Brasil",
    name_ar: "Brasil",
    name_cl: "Brasil",
    name_fr: "Brésil",
    name_gr: "Brasilien",
    name_it: "Brasile",
    name_pt: "Brasil",
    name_za: "Brasilië",
    name_in: "Brazil",
    name_id: "Brazil",
    name_ph: "Brazil",
    name_sg: "Brazil",
    name_es: "Brasil",
    flag: "🇧🇷",
    code: "BR",
    dial_code: "+55",
    phone_length: 11,
    white_listed: true,
  },
  {
    name: "British Indian Ocean Territory",
    name_br: "Território Britânico do Oceano Índico",
    name_mx: "Territorio Británico del Océano Índico",
    name_ar: "Territorio Británico del Océano Índico",
    name_cl: "Territorio Británico del Océano Índico",
    name_fr: "Territoire britannique de l'océan Indien",
    name_gr: "Britisches Territorium des Indischen Ozeans",
    name_it: "Territorio britannico dell'Oceano Indiano",
    name_pt: "Território Britânico do Oceano Índico",
    name_za: "Britse gebied in die Indiese Oseaan",
    name_in: "British Indian Ocean Territory",
    name_id: "Wilayah Samudra Hindia Britania",
    name_ph: "Teritoryo ng British Indian Ocean",
    name_sg: "British Indian Ocean Territory",
    name_es: "Territorio Británico del Océano Índico",
    flag: "🇮🇴",
    code: "IO",
    dial_code: "+246",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Brunei Darussalam",
    name_br: "Brunei Darussalam",
    name_mx: "Brunei Darussalam",
    name_ar: "Brunei Darussalam",
    name_cl: "Brunei Darussalam",
    name_fr: "Brunei Darussalam",
    name_gr: "Brunei Darussalam",
    name_it: "Brunei Darussalam",
    name_pt: "Brunei Darussalam",
    name_za: "Brunei Darussalam",
    name_in: "Brunei Darussalam",
    name_id: "Brunei Darussalam",
    name_ph: "Brunei Darussalam",
    name_sg: "Brunei Darussalam",
    name_es: "Brunei Darussalam",
    flag: "🇧🇳",
    code: "BN",
    dial_code: "+673",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Bulgaria",
    name_br: "Bulgária",
    name_mx: "Bulgaria",
    name_ar: "Bulgaria",
    name_cl: "Bulgaria",
    name_fr: "Bulgarie",
    name_gr: "Bulgarien",
    name_it: "Bulgaria",
    name_pt: "Bulgária",
    name_za: "Bulgarye",
    name_in: "Bulgaria",
    name_id: "Bulgaria",
    name_ph: "Bulgaria",
    name_sg: "Bulgaria",
    name_es: "Bulgaria",
    flag: "🇧🇬",
    code: "BG",
    dial_code: "+359",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Burkina Faso",
    name_br: "Burkina Faso",
    name_mx: "Burkina Faso",
    name_ar: "Burkina Faso",
    name_cl: "Burkina Faso",
    name_fr: "Burkina Faso",
    name_gr: "Burkina Faso",
    name_it: "Burkina Faso",
    name_pt: "Burkina Faso",
    name_za: "Burkina Faso",
    name_in: "Burkina Faso",
    name_id: "Burkina Faso",
    name_ph: "Burkina Faso",
    name_sg: "Burkina Faso",
    name_es: "Burkina Faso",
    flag: "🇧🇫",
    code: "BF",
    dial_code: "+226",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Burundi",
    name_br: "Burundi",
    name_mx: "Burundi",
    name_ar: "Burundi",
    name_cl: "Burundi",
    name_fr: "Burundi",
    name_gr: "Burundi",
    name_it: "Burundi",
    name_pt: "Burundi",
    name_za: "Burundi",
    name_in: "Burundi",
    name_id: "Burundi",
    name_ph: "Burundi",
    name_sg: "Burundi",
    name_es: "Burundi",
    flag: "🇧🇮",
    code: "BI",
    dial_code: "+257",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Cambodia",
    name_br: "Camboja",
    name_mx: "Camboya",
    name_ar: "Camboya",
    name_cl: "Camboya",
    name_fr: "Cambodge",
    name_gr: "Kambodscha",
    name_it: "Cambogia",
    name_pt: "Camboja",
    name_za: "Kambodja",
    name_in: "Cambodia",
    name_id: "Kamboja",
    name_ph: "Cambodia",
    name_sg: "Cambodia",
    name_es: "Camboya",
    flag: "🇰🇭",
    code: "KH",
    dial_code: "+855",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Cameroon",
    name_br: "Camarões",
    name_mx: "Camerún",
    name_ar: "Camerún",
    name_cl: "Camerún",
    name_fr: "Cameroun",
    name_gr: "Kamerun",
    name_it: "Camerun",
    name_pt: "Camarões",
    name_za: "Kameroen",
    name_in: "Cameroon",
    name_id: "Kamerun",
    name_ph: "Cameroon",
    name_sg: "Cameroon",
    name_es: "Camerún",
    flag: "🇨🇲",
    code: "CM",
    dial_code: "+237",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Canada",
    name_br: "Canadá",
    name_mx: "Canadá",
    name_ar: "Canadá",
    name_cl: "Canadá",
    name_fr: "Canada",
    name_gr: "Kanada",
    name_it: "Canada",
    name_pt: "Canadá",
    name_za: "Kanada",
    name_in: "Canada",
    name_id: "Kanada",
    name_ph: "Canada",
    name_sg: "Canada",
    name_es: "Canadá",
    flag: "🇨🇦",
    code: "CA",
    dial_code: "+1",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Cape Verde",
    name_br: "cabo Verde",
    name_mx: "Cabo Verde",
    name_ar: "Cabo Verde",
    name_cl: "Cabo Verde",
    name_fr: "Cap-Vert",
    name_gr: "Kap Verde",
    name_it: "capo Verde",
    name_pt: "cabo Verde",
    name_za: "Kaap Verde",
    name_in: "Cape Verde",
    name_id: "Tanjung Verde",
    name_ph: "Cape Verde",
    name_sg: "Cape Verde",
    name_es: "Cabo Verde",
    flag: "🇨🇻",
    code: "CV",
    dial_code: "+238",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Cayman Islands",
    name_br: "Ilhas Cayman",
    name_mx: "Islas Caimán",
    name_ar: "Islas Caimán",
    name_cl: "Islas Caimán",
    name_fr: "Îles Caïmans",
    name_gr: "Cayman Inseln",
    name_it: "Isole Cayman",
    name_pt: "Ilhas Cayman",
    name_za: "Cayman Eilande",
    name_in: "Cayman Islands",
    name_id: "Pulau cayman",
    name_ph: "Mga Isla ng Cayman",
    name_sg: "Cayman Islands",
    name_es: "Islas Caimán",
    flag: "🇰🇾",
    code: "KY",
    dial_code: "+345",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Central African Republic",
    name_br: "República Centro-Africana",
    name_mx: "República Centroafricana",
    name_ar: "República Centroafricana",
    name_cl: "República Centroafricana",
    name_fr: "République centrafricaine",
    name_gr: "Zentralafrikanische Republik",
    name_it: "Repubblica Centrafricana",
    name_pt: "República Centro-Africana",
    name_za: "Sentraal-Afrikaanse Republiek",
    name_in: "Central African Republic",
    name_id: "Republik Afrika Tengah",
    name_ph: "Republika ng Central Africa",
    name_sg: "Central African Republic",
    name_es: "República Centroafricana",
    flag: "🇨🇫",
    code: "CF",
    dial_code: "+236",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Chad",
    name_br: "Chade",
    name_mx: "Chad",
    name_ar: "Chad",
    name_cl: "Chad",
    name_fr: "Tchad",
    name_gr: "Tschad",
    name_it: "Chad",
    name_pt: "Chade",
    name_za: "Tsjad",
    name_in: "Chad",
    name_id: "Chad",
    name_ph: "Chad",
    name_sg: "Chad",
    name_es: "Chad",
    flag: "🇹🇩",
    code: "TD",
    dial_code: "+235",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Chile",
    name_br: "Chile",
    name_mx: "Chile",
    name_ar: "Chile",
    name_cl: "Chile",
    name_fr: "Chili",
    name_gr: "Chile",
    name_it: "Chile",
    name_pt: "Chile",
    name_za: "Chili",
    name_in: "Chile",
    name_id: "Chili",
    name_ph: "Chile",
    name_sg: "Chile",
    name_es: "Chile",
    flag: "🇨🇱",
    code: "CL",
    dial_code: "+56",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "China",
    name_br: "China",
    name_mx: "porcelana",
    name_ar: "porcelana",
    name_cl: "porcelana",
    name_fr: "Chine",
    name_gr: "China",
    name_it: "Cina",
    name_pt: "China",
    name_za: "Sjina",
    name_in: "China",
    name_id: "Cina",
    name_ph: "Tsina",
    name_sg: "China",
    name_es: "porcelana",
    flag: "🇨🇳",
    code: "CN",
    dial_code: "+86",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Christmas Island",
    name_br: "Ilha do Natal",
    name_mx: "Isla de Navidad",
    name_ar: "Isla de Navidad",
    name_cl: "Isla de Navidad",
    name_fr: "L'île de noël",
    name_gr: "Weihnachtsinsel",
    name_it: "Isola di Natale",
    name_pt: "Ilha do Natal",
    name_za: "Kerseiland",
    name_in: "Christmas Island",
    name_id: "Pulau Natal",
    name_ph: "Christmas Island",
    name_sg: "Christmas Island",
    name_es: "Isla de Navidad",
    flag: "🇨🇽",
    code: "CX",
    dial_code: "+61",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Cocos (Keeling) Islands",
    name_br: "Ilhas Cocos (Keeling)",
    name_mx: "Islas Cocos (Keeling)",
    name_ar: "Islas Cocos (Keeling)",
    name_cl: "Islas Cocos (Keeling)",
    name_fr: "Îles Cocos (Keeling)",
    name_gr: "Kokosinseln (Keelinginseln)",
    name_it: "Isole Cocos (Keeling)",
    name_pt: "Ilhas Cocos (Keeling)",
    name_za: "Cocos (Keeling) Eilande",
    name_in: "Cocos (Keeling) Islands",
    name_id: "Kepulauan Cocos (Keeling)",
    name_ph: "Cocos (Keeling) Islands",
    name_sg: "Cocos (Keeling) Islands",                                                  
    name_es: "Islas Cocos (Keeling)",
    flag: "🇨🇨",
    code: "CC",
    dial_code: "+61",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Colombia",
    name_br: "Colômbia",
    name_mx: "Colombia",
    name_ar: "Colombia",
    name_cl: "Colombia",
    name_fr: "Colombie",
    name_gr: "Kolumbien",
    name_it: "Colombia",
    name_pt: "Colômbia",
    name_za: "Colombia",
    name_in: "Colombia",
    name_id: "Kolumbia",
    name_ph: "Colombia",
    name_sg: "Colombia",
    name_es: "Colombia",
    flag: "🇨🇴",
    code: "CO",
    dial_code: "+57",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Comoros",
    name_br: "Comores",
    name_mx: "Comoras",
    name_ar: "Comoras",
    name_cl: "Comoras",
    name_fr: "Comores",
    name_gr: "Komoren",
    name_it: "Comore",
    name_pt: "Comores",
    name_za: "Komore",
    name_in: "Comoros",
    name_id: "Komoro",
    name_ph: "Mga Comoro",
    name_sg: "Comoros",
    name_es: "Comoras",
    flag: "🇰🇲",
    code: "KM",
    dial_code: "+269",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Congo",
    name_br: "Congo",
    name_mx: "Congo",
    name_ar: "Congo",
    name_cl: "Congo",
    name_fr: "Congolais",
    name_gr: "Kongo",
    name_it: "Congo",
    name_pt: "Congo",
    name_za: "Kongo",
    name_in: "Congo",
    name_id: "Kongo",
    name_ph: "Kongo",
    name_sg: "Congo",
    name_es: "Congo",
    flag: "🇨🇬",
    code: "CG",
    dial_code: "+242",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    name_br: "Congo, República Democrática do Congo",
    name_mx: "Congo, República Democrática del Congo",
    name_ar: "Congo, República Democrática del Congo",
    name_cl: "Congo, República Democrática del Congo",
    name_fr: "Congo, République démocratique du Congo",
    name_gr: "Kongo, Demokratische Republik Kongo",
    name_it: "Congo, Repubblica Democratica del Congo",
    name_pt: "Congo, República Democrática do Congo",
    name_za: "Kongo, die Demokratiese Republiek van die Kongo",
    name_in: "Congo, The Democratic Republic of the Congo",
    name_id: "Kongo, Republik Demokratik Kongo",
    name_ph: "Congo, Ang Demokratikong Republika ng Congo",
    name_sg: "Congo, The Democratic Republic of the Congo",
    name_es: "Congo, República Democrática del Congo",
    flag: "🇨🇩",
    code: "CD",
    dial_code: "+243",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Cook Islands",
    name_br: "Ilhas Cook",
    name_mx: "Islas Cook",
    name_ar: "Islas Cook",
    name_cl: "Islas Cook",
    name_fr: "les Îles Cook",
    name_gr: "Cookinseln",
    name_it: "Isole Cook",
    name_pt: "Ilhas Cook",
    name_za: "Cook Eilande",
    name_in: "Cook Islands",
    name_id: "Kepulauan Cook",
    name_ph: "mga Isla ng Cook",
    name_sg: "Cook Islands",
    name_es: "Islas Cook",
    flag: "🇨🇰",
    code: "CK",
    dial_code: "+682",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Costa Rica",
    name_br: "Costa Rica",
    name_mx: "Costa Rica",
    name_ar: "Costa Rica",
    name_cl: "Costa Rica",
    name_fr: "Congolais",
    name_gr: "Costa Rica",
    name_it: "Costa Rica",
    name_pt: "Costa Rica",
    name_za: "Costa Rica",
    name_in: "Costa Rica",
    name_id: "Kosta Rika",
    name_ph: "Costa Rica",
    name_sg: "Costa Rica",
    name_es: "Costa Rica",
    flag: "🇨🇷",
    code: "CR",
    dial_code: "+506",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Cote d'Ivoire",
    name_br: "Costa do Marfim",
    name_mx: "Costa de Marfil",
    name_ar: "Costa de Marfil",
    name_cl: "Costa de Marfil",
    name_fr: "Côte d'Ivoire",
    name_gr: "Elfenbeinküste",
    name_it: "Costa d'Avorio",
    name_pt: "Costa do Marfim",
    name_za: "Ivoorkus",
    name_in: "Cote d'Ivoire",
    name_id: "Pantai Gading",
    name_ph: "Cote d'Ivoire",
    name_sg: "Cote d'Ivoire",
    name_es: "Costa de Marfil",
    flag: "🇨🇮",
    code: "CI",
    dial_code: "+225",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Croatia",
    name_br: "Croácia",
    name_mx: "Croacia",
    name_ar: "Croacia",
    name_cl: "Croacia",
    name_fr: "Croatie",
    name_gr: "Kroatien",
    name_it: "Croazia",
    name_pt: "Croácia",
    name_za: "Croazia",
    name_in: "Croatia",
    name_id: "Kroasia",
    name_ph: "Croatia",
    name_sg: "Croatia",
    name_es: "Croacia",
    flag: "🇭🇷",
    code: "HR",
    dial_code: "+385",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Cuba",
    name_br: "Cuba",
    name_mx: "Cuba",
    name_ar: "Cuba",
    name_cl: "Cuba",
    name_fr: "Cuba",
    name_gr: "Kuba",
    name_it: "Cuba",
    name_pt: "Cuba",
    name_za: "Kuba",
    name_in: "Cuba",
    name_id: "Kuba",
    name_ph: "Cuba",
    name_sg: "Cuba",
    name_es: "Cuba",
    flag: "🇨🇺",
    code: "CU",
    dial_code: "+53",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Cyprus",
    name_br: "Chipre",
    name_mx: "Chipre",
    name_ar: "Chipre",
    name_cl: "Chipre",
    name_fr: "Chypre",
    name_gr: "Zypern",
    name_it: "Cipro",
    name_pt: "Chipre",
    name_za: "Ciprus",
    name_in: "Cyprus",
    name_id: "Siprus",
    name_ph: "Siprus",
    name_sg: "Cyprus",
    name_es: "Chipre",
    flag: "🇨🇾",
    code: "CY",
    dial_code: "+357",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Czech Republic",
    name_br: "República Checa",
    name_mx: "República Checa",
    name_ar: "República Checa",
    name_cl: "República Checa",
    name_fr: "République Tchèque",
    name_gr: "Tschechien",
    name_it: "Repubblica Ceca",
    name_pt: "República Checa",
    name_za: "Tsjeggiese Republiek",
    name_in: "Czech Republic",
    name_id: "Republik Ceko",
    name_ph: "Czech Republic",
    name_sg: "Czech Republic",
    name_es: "República Checa",
    flag: "🇨🇿",
    code: "CZ",
    dial_code: "+420",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Denmark",
    name_br: "Dinamarca",
    name_mx: "Dinamarca",
    name_ar: "Dinamarca",
    name_cl: "Dinamarca",
    name_fr: "Danemark",
    name_gr: "Dänemark",
    name_it: "Danimarca",
    name_pt: "Dinamarca",
    name_za: "Denemarke",
    name_in: "Denmark",
    name_id: "Denmark",
    name_ph: "Denmark",
    name_sg: "Denmark",
    name_es: "Dinamarca",
    flag: "🇩🇰",
    code: "DK",
    dial_code: "+45",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Djibouti",
    name_br: "Djibouti",
    name_mx: "Djibouti",
    name_ar: "Djibouti",
    name_cl: "Djibouti",
    name_fr: "Djibouti",
    name_gr: "Dschibuti",
    name_it: "Gibuti",
    name_pt: "Djibouti",
    name_za: "Djiboeti",
    name_in: "Djibouti",
    name_id: "Djibouti",
    name_ph: "Djibouti",
    name_sg: "Djibouti",
    name_es: "Djibouti",
    flag: "🇩🇯",
    code: "DJ",
    dial_code: "+253",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Dominica",
    name_br: "Dominica",
    name_mx: "Dominica",
    name_ar: "Dominica",
    name_cl: "Dominica",
    name_fr: "Dominique",
    name_gr: "Dominica",
    name_it: "Dominica",
    name_pt: "Dominica",
    name_za: "Dominica",
    name_in: "Dominica",
    name_id: "Dominika",
    name_ph: "Dominica",
    name_sg: "Dominica",
    name_es: "Dominica",
    flag: "🇩🇲",
    code: "DM",
    dial_code: "+1767",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Dominican Republic",
    name_br: "República Dominicana",
    name_mx: "República Dominicana",
    name_ar: "República Dominicana",
    name_cl: "República Dominicana",
    name_fr: "République Dominicaine",
    name_gr: "Dominikanische Republik",
    name_it: "Repubblica Dominicana",
    name_pt: "República Dominicana",
    name_za: "Dominikaanse Republiek",
    name_in: "Dominican Republic",
    name_id: "Republik Dominika",
    name_ph: "Dominican Republic",
    name_sg: "Dominican Republic",
    name_es: "República Dominicana",
    flag: "🇩🇴",
    code: "DO",
    dial_code: "+1849",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Ecuador",
    name_br: "Equador",
    name_mx: "Ecuador",
    name_ar: "Ecuador",
    name_cl: "Ecuador",
    name_fr: "Équateur",
    name_gr: "Ecuador",
    name_it: "Ecuador",
    name_pt: "Equador",
    name_za: "Ecuador",
    name_in: "Ecuador",
    name_id: "Ekuador",
    name_ph: "Ecuador",
    name_sg: "Ecuador",
    name_es: "Ecuador",
    flag: "🇪🇨",
    code: "EC",
    dial_code: "+593",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Egypt",
    name_br: "Egito",
    name_mx: "Egipto",
    name_ar: "Egipto",
    name_cl: "Egipto",
    name_fr: "Egypte",
    name_gr: "Ägypten",
    name_it: "Egitto",
    name_pt: "Egito",
    name_za: "Egipte",
    name_in: "Egypt",
    name_id: "Mesir",
    name_ph: "Egypt",
    name_sg: "Egypt",
    name_es: "Egipto",
    flag: "🇪🇬",
    code: "EG",
    dial_code: "+20",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "El Salvador",
    name_br: "El Salvador",
    name_mx: "El Salvador",
    name_ar: "El Salvador",
    name_cl: "El Salvador",
    name_fr: "Le Salvador",
    name_gr: "El Salvador",
    name_it: "El Salvador",
    name_pt: "El Salvador",
    name_za: "El Salvador",
    name_in: "El Salvador",
    name_id: "El Salvador",
    name_ph: "El Salvador",
    name_sg: "El Salvador",
    name_es: "El Salvador",
    flag: "🇸🇻",
    code: "SV",
    dial_code: "+503",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Equatorial Guinea",
    name_br: "Guiné Equatorial",
    name_mx: "Guinea Ecuatorial",
    name_ar: "Guinea Ecuatorial",
    name_cl: "Guinea Ecuatorial",
    name_fr: "Guinée Équatoriale",
    name_gr: "Äquatorialguinea",
    name_it: "Guinea Equatoriale",
    name_pt: "Guiné Equatorial",
    name_za: "Ekwatoriaal-Guinee",
    name_in: "Equatorial Guinea",
    name_id: "Guinea ekuator",
    name_ph: "Equatorial Guinea",
    name_sg: "Equatorial Guinea",
    name_es: "Guinea Ecuatorial",
    flag: "🇬🇶",
    code: "GQ",
    dial_code: "+240",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Eritrea",
    name_br: "Eritreia",
    name_mx: "Eritrea",
    name_ar: "Eritrea",
    name_cl: "Eritrea",
    name_fr: "Érythrée",
    name_gr: "Ägypten",
    name_it: "Egitto",
    name_pt: "Eritreia",
    name_za: "Eritrea",
    name_in: "Eritrea",
    name_id: "Eritrea",
    name_ph: "Eritrea",
    name_sg: "Eritrea",
    name_es: "Eritrea",
    flag: "🇪🇷",
    code: "ER",
    dial_code: "+291",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Estonia",
    name_br: "Estônia",
    name_mx: "Estonia",
    name_ar: "Estonia",
    name_cl: "Estonia",
    name_fr: "Estonie",
    name_gr: "Estland",
    name_it: "Estonia",
    name_pt: "Estônia",
    name_za: "Estland",
    name_in: "Estonia",
    name_id: "Estonia",
    name_ph: "Estonia",
    name_sg: "Estonia",
    name_es: "Estonia",
    flag: "🇪🇪",
    code: "EE",
    dial_code: "+372",
    phone_length: 7,
    white_listed: true,
  },
  {
    name: "Ethiopia",
    name_br: "Etiópia",
    name_mx: "Etiopía",
    name_ar: "Etiopía",
    name_cl: "Etiopía",
    name_fr: "Ethiopie",
    name_gr: "Äthiopien",
    name_it: "Etiopia",
    name_pt: "Etiópia",
    name_za: "Ethiopië",
    name_in: "Ethiopia",
    name_id: "Etiopia",
    name_ph: "Ethiopia",
    name_sg: "Ethiopia",
    name_es: "Etiopía",
    flag: "🇪🇹",
    code: "ET",
    dial_code: "+251",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Falkland Islands (Malvinas)",
    name_br: "Ilhas Falkland (Malvinas)",
    name_mx: "Islas Malvinas",
    name_ar: "Islas Malvinas",
    name_cl: "Islas Malvinas",
    name_fr: "Îles Falkland (Malvinas)",
    name_gr: "Falklandinseln (Malvinas)",
    name_it: "Isole Falkland (Malvine)",
    name_pt: "Ilhas Falkland (Malvinas)",
    name_za: "Falkland-eilande (Malvinas)",
    name_in: "Falkland Islands (Malvinas)",
    name_id: "Kepulauan Falkland (Malvinas)",
    name_ph: "Falkland Islands (Malvinas)",
    name_sg: "Falkland Islands (Malvinas)",
    name_es: "Islas Malvinas",
    flag: "🇫🇰",
    code: "FK",
    dial_code: "+500",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Faroe Islands",
    name_br: "ilhas Faroe",
    name_mx: "Islas Faroe",
    name_ar: "Islas Faroe",
    name_cl: "Islas Faroe",
    name_fr: "Îles Féroé",
    name_gr: "Färöer Inseln",
    name_it: "Isole Faroe",
    name_pt: "ilhas Faroe",
    name_za: "Faroëreilande",
    name_in: "Faroe Islands",
    name_id: "Kepulauan Faroe",
    name_ph: "isla ng Faroe",
    name_sg: "Faroe Islands",
    name_es: "Islas Faroe",
    flag: "🇫🇴",
    code: "FO",
    dial_code: "+298",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Fiji",
    name_br: "Fiji",
    name_mx: "Fiyi",
    name_ar: "Fiyi",
    name_cl: "Fiyi",
    name_fr: "Fidji",
    name_gr: "Fidschi",
    name_it: "Figi",
    name_pt: "Fiji",
    name_za: "Fidji",
    name_in: "Fiji",
    name_id: "Fiji",
    name_ph: "Fiji",
    name_sg: "Fiji",
    name_es: "Fiyi",
    flag: "🇫🇯",
    code: "FJ",
    dial_code: "+679",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Finland",
    name_br: "Finlândia",
    name_mx: "Finlandia",
    name_ar: "Finlandia",
    name_cl: "Finlandia",
    name_fr: "Finlande",
    name_gr: "Finnland",
    name_it: "Finlandia",
    name_pt: "Finlândia",
    name_za: "Finland",
    name_in: "Finland",
    name_id: "Finlandia",
    name_ph: "Pinlandiya",
    name_sg: "Finland",
    name_es: "Finlandia",
    flag: "🇫🇮",
    code: "FI",
    dial_code: "+358",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "France",
    name_br: "França",
    name_mx: "Francia",
    name_ar: "Francia",
    name_cl: "Francia",
    name_fr: "France",
    name_gr: "Frankreich",
    name_it: "Francia",
    name_pt: "França",
    name_za: "Frankryk",
    name_in: "France",
    name_id: "Perancis",
    name_ph: "France",
    name_sg: "France",
    name_es: "Francia",
    flag: "🇫🇷",
    code: "FR",
    dial_code: "+33",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "French Guiana",
    name_br: "Guiana Francesa",
    name_mx: "Guayana Francesa",
    name_ar: "Guayana Francesa",
    name_cl: "Guayana Francesa",
    name_fr: "Guyane Française",
    name_gr: "Französisch-Guayana",
    name_it: "Guiana francese",
    name_pt: "Guiana Francesa",
    name_za: "Frans-Guyana",
    name_in: "French Guiana",
    name_id: "Guyana Perancis",
    name_ph: "French Guiana",
    name_sg: "French Guiana",
    name_es: "Guayana Francesa",
    flag: "🇬🇫",
    code: "GF",
    dial_code: "+594",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "French Polynesia",
    name_br: "Polinésia Francesa",
    name_mx: "Polinesia francés",
    name_ar: "Polinesia francés",
    name_cl: "Polinesia francés",
    name_fr: "Polynésie française",
    name_gr: "Französisch Polynesien",
    name_it: "Polinesia francese",
    name_pt: "Polinésia Francesa",
    name_za: "Frans-Polynesië",
    name_in: "French Polynesia",
    name_id: "Polinesia Perancis",
    name_ph: "French Polynesia",
    name_sg: "French Polynesia",
    name_es: "Polinesia francés",
    flag: "🇵🇫",
    code: "PF",
    dial_code: "+689",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "French Southern Territories",
    name_br: "Territórios Franceses do Sul",
    name_mx: "Territorios Franceses del Sur",
    name_ar: "Territorios Franceses del Sur",
    name_cl: "Territorios Franceses del Sur",
    name_fr: "Terres Australes Françaises",
    name_gr: "Südfranzösische Territorien",
    name_it: "Territori della Francia del sud",
    name_pt: "Territórios Franceses do Sul",
    name_za: "Franse suidelike gebiede",
    name_in: "French Southern Territories",
    name_id: "Wilayah Selatan Prancis",
    name_ph: "Mga Teritoryo sa Timog na Pransya",
    name_sg: "French Southern Territories",
    name_es: "Territorios Franceses del Sur",
    flag: "🇹🇫",
    code: "TF",
    dial_code: "+262",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Gabon",
    name_br: "Gabão",
    name_mx: "Gabón",
    name_ar: "Gabón",
    name_cl: "Gabón",
    name_fr: "Gabon",
    name_gr: "Gabun",
    name_it: "Gabon",
    name_pt: "Gabão",
    name_za: "Gaboen",
    name_in: "Gabon",
    name_id: "Gabon",
    name_ph: "Gabon",
    name_sg: "Gabon",
    name_es: "Gabón",
    flag: "🇬🇦",
    code: "GA",
    dial_code: "+241",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Gambia",
    name_br: "Gâmbia",
    name_mx: "Gambia",
    name_ar: "Gambia",
    name_cl: "Gambia",
    name_fr: "Gambie",
    name_gr: "Gambia",
    name_it: "Gambia",
    name_pt: "Gambia",
    name_za: "Gambië",
    name_in: "Gambia",
    name_id: "Gambia",
    name_ph: "Gambia",
    name_sg: "Gambia",
    name_es: "Gambia",
    flag: "🇬🇲",
    code: "GM",
    dial_code: "+220",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Georgia",
    name_br: "Georgia",
    name_mx: "Georgia",
    name_ar: "Georgia",
    name_cl: "Georgia",
    name_fr: "Géorgie",
    name_gr: "Georgia",
    name_it: "Georgia",
    name_pt: "Georgia",
    name_za: "Georgië",
    name_in: "Georgia",
    name_id: "Georgia",
    name_ph: "Georgia",
    name_sg: "Georgia",
    name_es: "Georgia",
    flag: "🇬🇪",
    code: "GE",
    dial_code: "+995",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Germany",
    name_br: "Alemanha",
    name_mx: "Alemania",
    name_ar: "Alemania",
    name_cl: "Alemania",
    name_fr: "Allemagne",
    name_gr: "Deutschland",
    name_it: "Germania",
    name_pt: "Alemanha",
    name_za: "Duitsland",
    name_in: "Germany",
    name_id: "Jerman",
    name_ph: "Alemanya",
    name_sg: "Germany",
    name_es: "Alemania",
    flag: "🇩🇪",
    code: "DE",
    dial_code: "+49",
    phone_length: 11,
    white_listed: true,
  },
  {
    name: "Ghana",
    name_br: "Gana",
    name_mx: "Ghana",
    name_ar: "Ghana",
    name_cl: "Ghana",
    name_fr: "Ghana",
    name_gr: "Ghana",
    name_it: "Ghana",
    name_pt: "Gana",
    name_za: "Ghana",
    name_in: "Ghana",
    name_id: "Ghana",
    name_ph: "Ghana",
    name_sg: "Ghana",
    name_es: "Ghana",
    flag: "🇬🇭",
    code: "GH",
    dial_code: "+233",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Gibraltar",
    name_br: "Georgia",
    name_mx: "Georgia",
    name_ar: "Georgia",
    name_cl: "Georgia",
    name_fr: "Géorgie",
    name_gr: "Georgia",
    name_it: "Georgia",
    name_pt: "Georgia",
    name_za: "Georgië",
    name_in: "Georgia",
    name_id: "Georgia",
    name_ph: "Georgia",
    name_sg: "Georgia",
    name_es: "Georgia",
    flag: "🇬🇮",
    code: "GI",
    dial_code: "+350",
    phone_length: 5,
    white_listed: true,
  },
  {
    name: "Greece",
    flag: "🇬🇷",
    code: "GR",
    dial_code: "+30",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Greenland",
    flag: "🇬🇱",
    code: "GL",
    dial_code: "+299",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Grenada",
    flag: "🇬🇩",
    code: "GD",
    dial_code: "+1473",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Guadeloupe",
    flag: "🇬🇵",
    code: "GP",
    dial_code: "+590",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Guam",
    flag: "🇬🇺",
    code: "GU",
    dial_code: "+1671",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Guatemala",
    flag: "🇬🇹",
    code: "GT",
    dial_code: "+502",
    phone_length: 7,
    white_listed: true,
  },
  {
    name: "Guernsey",
    flag: "🇬🇬",
    code: "GG",
    dial_code: "+44",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Guinea",
    flag: "🇬🇳",
    code: "GN",
    dial_code: "+224",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    code: "GW",
    dial_code: "+245",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Guyana",
    flag: "🇬🇾",
    code: "GY",
    dial_code: "+592",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Haiti",
    flag: "🇭🇹",
    code: "HT",
    dial_code: "+509",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Heard Island and Mcdonald Islands",
    flag: "🇭🇲",
    code: "HM",
    dial_code: "+672",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Holy See (Vatican City State)",
    flag: "🇻🇦",
    code: "VA",
    dial_code: "+379",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Honduras",
    flag: "🇭🇳",
    code: "HN",
    dial_code: "+504",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Hong Kong",
    flag: "🇭🇰",
    code: "HK",
    dial_code: "+852",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Hungary",
    flag: "🇭🇺",
    code: "HU",
    dial_code: "+36",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Iceland",
    flag: "🇮🇸",
    code: "IS",
    dial_code: "+354",
    phone_length: 7,
    white_listed: true,
  },
  {
    name: "India",
    flag: "🇮🇳",
    code: "IN",
    dial_code: "+91",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Indonesia",
    flag: "🇮🇩",
    code: "ID",
    dial_code: "+62",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    flag: "🇮🇷",
    code: "IR",
    dial_code: "+98",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Iraq",
    flag: "🇮🇶",
    code: "IQ",
    dial_code: "+964",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Ireland",
    flag: "🇮🇪",
    code: "IE",
    dial_code: "+353",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Isle of Man",
    flag: "🇮🇲",
    code: "IM",
    dial_code: "+44",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Israel",
    flag: "🇮🇱",
    code: "IL",
    dial_code: "+972",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Italy",
    flag: "🇮🇹",
    code: "IT",
    dial_code: "+39",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Jamaica",
    flag: "🇯🇲",
    code: "JM",
    dial_code: "+1876",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Japan",
    flag: "🇯🇵",
    code: "JP",
    dial_code: "+81",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Jersey",
    flag: "🇯🇪",
    code: "JE",
    dial_code: "+44",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Jordan",
    flag: "🇯🇴",
    code: "JO",
    dial_code: "+962",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Kazakhstan",
    flag: "🇰🇿",
    code: "KZ",
    dial_code: "+7",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Kenya",
    flag: "🇰🇪",
    code: "KE",
    dial_code: "+254",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Kiribati",
    flag: "🇰🇮",
    code: "KI",
    dial_code: "+686",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    flag: "🇰🇵",
    code: "KP",
    dial_code: "+850",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Korea, Republic of South Korea",
    flag: "🇰🇷",
    code: "KR",
    dial_code: "+82",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Kosovo",
    flag: "🇽🇰",
    code: "XK",
    dial_code: "+383",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Kuwait",
    flag: "🇰🇼",
    code: "KW",
    dial_code: "+965",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    code: "KG",
    dial_code: "+996",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Laos",
    flag: "🇱🇦",
    code: "LA",
    dial_code: "+856",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Latvia",
    flag: "🇱🇻",
    code: "LV",
    dial_code: "+371",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Lebanon",
    flag: "🇱🇧",
    code: "LB",
    dial_code: "+961",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Lesotho",
    flag: "🇱🇸",
    code: "LS",
    dial_code: "+266",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Liberia",
    flag: "🇱🇷",
    code: "LR",
    dial_code: "+231",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Libyan Arab Jamahiriya",
    flag: "🇱🇾",
    code: "LY",
    dial_code: "+218",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Liechtenstein",
    flag: "🇱🇮",
    code: "LI",
    dial_code: "+423",
    phone_length: 7,
    white_listed: true,
  },
  {
    name: "Lithuania",
    flag: "🇱🇹",
    code: "LT",
    dial_code: "+370",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Luxembourg",
    flag: "🇱🇺",
    code: "LU",
    dial_code: "+352",
    phone_length: 6,
    white_listed: true,
  },
  {
    name: "Macao",
    flag: "🇲🇴",
    code: "MO",
    dial_code: "+853",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Macedonia",
    flag: "🇲🇰",
    code: "MK",
    dial_code: "+389",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Madagascar",
    flag: "🇲🇬",
    code: "MG",
    dial_code: "+261",
    phone_length: 7,
    white_listed: true,
  },
  {
    name: "Malawi",
    flag: "🇲🇼",
    code: "MW",
    dial_code: "+265",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Malaysia",
    flag: "🇲🇾",
    code: "MY",
    dial_code: "+60",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Maldives",
    flag: "🇲🇻",
    code: "MV",
    dial_code: "+960",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Mali",
    flag: "🇲🇱",
    code: "ML",
    dial_code: "+223",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Malta",
    flag: "🇲🇹",
    code: "MT",
    dial_code: "+356",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Marshall Islands",
    flag: "🇲🇭",
    code: "MH",
    dial_code: "+692",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Martinique",
    flag: "🇲🇶",
    code: "MQ",
    dial_code: "+596",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Mauritania",
    flag: "🇲🇷",
    code: "MR",
    dial_code: "+222",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Mauritius",
    flag: "🇲🇺",
    code: "MU",
    dial_code: "+230",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Mayotte",
    flag: "🇾🇹",
    code: "YT",
    dial_code: "+262",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Mexico",
    flag: "🇲🇽",
    code: "MX",
    dial_code: "+52",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    flag: "🇫🇲",
    code: "FM",
    dial_code: "+691",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Moldova",
    flag: "🇲🇩",
    code: "MD",
    dial_code: "+373",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Monaco",
    flag: "🇲🇨",
    code: "MC",
    dial_code: "+377",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Mongolia",
    flag: "🇲🇳",
    code: "MN",
    dial_code: "+976",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Montenegro",
    flag: "🇲🇪",
    code: "ME",
    dial_code: "+382",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Montserrat",
    flag: "🇲🇸",
    code: "MS",
    dial_code: "+1664",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Morocco",
    flag: "🇲🇦",
    code: "MA",
    dial_code: "+212",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Mozambique",
    flag: "🇲🇿",
    code: "MZ",
    dial_code: "+258",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Myanmar",
    flag: "🇲🇲",
    code: "MM",
    dial_code: "+95",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Namibia",
    flag: "🇳🇦",
    code: "NA",
    dial_code: "+264",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Nauru",
    flag: "🇳🇷",
    code: "NR",
    dial_code: "+674",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Nepal",
    flag: "🇳🇵",
    code: "NP",
    dial_code: "+977",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    code: "NL",
    dial_code: "+31",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Netherlands Antilles",
    flag: "",
    code: "AN",
    dial_code: "+599",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "New Caledonia",
    flag: "🇳🇨",
    code: "NC",
    dial_code: "+687",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "New Zealand",
    flag: "🇳🇿",
    code: "NZ",
    dial_code: "+64",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Nicaragua",
    flag: "🇳🇮",
    code: "NI",
    dial_code: "+505",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Niger",
    flag: "🇳🇪",
    code: "NE",
    dial_code: "+227",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Nigeria",
    flag: "🇳🇬",
    code: "NG",
    dial_code: "+234",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Niue",
    flag: "🇳🇺",
    code: "NU",
    dial_code: "+683",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Norfolk Island",
    flag: "🇳🇫",
    code: "NF",
    dial_code: "+672",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
    code: "MP",
    dial_code: "+1670",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Norway",
    flag: "🇳🇴",
    code: "NO",
    dial_code: "+47",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Oman",
    flag: "🇴🇲",
    code: "OM",
    dial_code: "+968",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Pakistan",
    flag: "🇵🇰",
    code: "PK",
    dial_code: "+92",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Palau",
    flag: "🇵🇼",
    code: "PW",
    dial_code: "+680",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Palestinian Territory, Occupied",
    flag: "🇵🇸",
    code: "PS",
    dial_code: "+970",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Panama",
    flag: "🇵🇦",
    code: "PA",
    dial_code: "+507",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Papua New Guinea",
    flag: "🇵🇬",
    code: "PG",
    dial_code: "+675",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Paraguay",
    flag: "🇵🇾",
    code: "PY",
    dial_code: "+595",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Peru",
    flag: "🇵🇪",
    code: "PE",
    dial_code: "+51",
    phone_length: 11,
    white_listed: true,
  },
  {
    name: "Philippines",
    flag: "🇵🇭",
    code: "PH",
    dial_code: "+63",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Pitcairn",
    flag: "🇵🇳",
    code: "PN",
    dial_code: "+64",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Poland",
    flag: "🇵🇱",
    code: "PL",
    dial_code: "+48",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Portugal",
    flag: "🇵🇹",
    code: "PT",
    dial_code: "+351",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Puerto Rico",
    flag: "🇵🇷",
    code: "PR",
    dial_code: "+1939",
    phone_length: 7,
    white_listed: true,
  },
  {
    name: "Qatar",
    flag: "🇶🇦",
    code: "QA",
    dial_code: "+974",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Romania",
    flag: "🇷🇴",
    code: "RO",
    dial_code: "+40",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Russia",
    flag: "🇷🇺",
    code: "RU",
    dial_code: "+7",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Rwanda",
    flag: "🇷🇼",
    code: "RW",
    dial_code: "+250",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Reunion",
    flag: "🇷🇪",
    code: "RE",
    dial_code: "+262",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saint Barthelemy",
    flag: "🇧🇱",
    code: "BL",
    dial_code: "+590",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "🇸🇭",
    code: "SH",
    dial_code: "+290",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    code: "KN",
    dial_code: "+1869",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saint Lucia",
    flag: "🇱🇨",
    code: "LC",
    dial_code: "+1758",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saint Martin",
    flag: "🇲🇫",
    code: "MF",
    dial_code: "+590",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    code: "PM",
    dial_code: "+508",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    code: "VC",
    dial_code: "+1784",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Samoa",
    flag: "🇼🇸",
    code: "WS",
    dial_code: "+685",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "San Marino",
    flag: "🇸🇲",
    code: "SM",
    dial_code: "+378",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    code: "ST",
    dial_code: "+239",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Saudi Arabia",
    flag: "🇸🇦",
    code: "SA",
    dial_code: "+966",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Senegal",
    flag: "🇸🇳",
    code: "SN",
    dial_code: "+221",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Serbia",
    flag: "🇷🇸",
    code: "RS",
    dial_code: "+381",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Seychelles",
    flag: "🇸🇨",
    code: "SC",
    dial_code: "+248",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Sierra Leone",
    flag: "🇸🇱",
    code: "SL",
    dial_code: "+232",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Singapore",
    flag: "🇸🇬",
    code: "SG",
    dial_code: "+65",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Slovakia",
    flag: "🇸🇰",
    code: "SK",
    dial_code: "+421",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Slovenia",
    flag: "🇸🇮",
    code: "SI",
    dial_code: "+386",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Solomon Islands",
    flag: "🇸🇧",
    code: "SB",
    dial_code: "+677",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Somalia",
    flag: "🇸🇴",
    code: "SO",
    dial_code: "+252",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "South Africa",
    flag: "🇿🇦",
    code: "ZA",
    dial_code: "+27",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "South Sudan",
    flag: "🇸🇸",
    code: "SS",
    dial_code: "+211",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    code: "GS",
    dial_code: "+500",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Spain",
    flag: "🇪🇸",
    code: "ES",
    dial_code: "+34",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Sri Lanka",
    flag: "🇱🇰",
    code: "LK",
    dial_code: "+94",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Sudan",
    flag: "🇸🇩",
    code: "SD",
    dial_code: "+249",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Suriname",
    flag: "🇸🇷",
    code: "SR",
    dial_code: "+597",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    code: "SJ",
    dial_code: "+47",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Swaziland",
    flag: "🇸🇿",
    code: "SZ",
    dial_code: "+268",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Sweden",
    flag: "🇸🇪",
    code: "SE",
    dial_code: "+46",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Switzerland",
    flag: "🇨🇭",
    code: "CH",
    dial_code: "+41",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Syrian Arab Republic",
    flag: "🇸🇾",
    code: "SY",
    dial_code: "+963",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Taiwan",
    flag: "🇹🇼",
    code: "TW",
    dial_code: "+886",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Tajikistan",
    flag: "🇹🇯",
    code: "TJ",
    dial_code: "+992",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    flag: "🇹🇿",
    code: "TZ",
    dial_code: "+255",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Thailand",
    flag: "🇹🇭",
    code: "TH",
    dial_code: "+66",
    phone_length: 8,
    white_listed: true,
  },
  {
    name: "Timor-Leste",
    flag: "🇹🇱",
    code: "TL",
    dial_code: "+670",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Togo",
    flag: "🇹🇬",
    code: "TG",
    dial_code: "+228",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Tokelau",
    flag: "🇹🇰",
    code: "TK",
    dial_code: "+690",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Tonga",
    flag: "🇹🇴",
    code: "TO",
    dial_code: "+676",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    code: "TT",
    dial_code: "+1868",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Tunisia",
    flag: "🇹🇳",
    code: "TN",
    dial_code: "+216",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Turkey",
    flag: "🇹🇷",
    code: "TR",
    dial_code: "+90",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Turkmenistan",
    flag: "🇹🇲",
    code: "TM",
    dial_code: "+993",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Turks and Caicos Islands",
    flag: "🇹🇨",
    code: "TC",
    dial_code: "+1649",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Tuvalu",
    flag: "🇹🇻",
    code: "TV",
    dial_code: "+688",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Uganda",
    flag: "🇺🇬",
    code: "UG",
    dial_code: "+256",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Ukraine",
    flag: "🇺🇦",
    code: "UA",
    dial_code: "+380",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "United Arab Emirates",
    flag: "🇦🇪",
    code: "AE",
    dial_code: "+971",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "United Kingdom",
    flag: "🇬🇧",
    code: "GB",
    dial_code: "+44",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "United States",
    flag: "🇺🇸",
    code: "US",
    dial_code: "+1",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "United States Outlying Islands",
    flag: "🇺🇸",
    code: "US",
    dial_code: "+246",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Uruguay",
    flag: "🇺🇾",
    code: "UY",
    dial_code: "+598",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Uzbekistan",
    flag: "🇺🇿",
    code: "UZ",
    dial_code: "+998",
    phone_length: 9,
    white_listed: true,
  },
  {
    name: "Vanuatu",
    flag: "🇻🇺",
    code: "VU",
    dial_code: "+678",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "🇻🇪",
    code: "VE",
    dial_code: "+58",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Vietnam",
    flag: "🇻🇳",
    code: "VN",
    dial_code: "+84",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Virgin Islands, British",
    flag: "🇻🇬",
    code: "VG",
    dial_code: "+1284",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Virgin Islands, U.S.",
    flag: "🇻🇮",
    code: "VI",
    dial_code: "+1340",
    phone_length: 10,
    white_listed: true,
  },
  {
    name: "Wallis and Futuna",
    flag: "🇼🇫",
    code: "WF",
    dial_code: "+681",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Yemen",
    flag: "🇾🇪",
    code: "YE",
    dial_code: "+967",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Zambia",
    flag: "🇿🇲",
    code: "ZM",
    dial_code: "+260",
    phone_length: 10,
    white_listed: false,
  },
  {
    name: "Zimbabwe",
    flag: "🇿🇼",
    code: "ZW",
    dial_code: "+263",
    phone_length: 10,
    white_listed: false,
  },
];
